name: CI Builds

on: [push, pull_request]

permissions:
  contents: write

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        shell: bash
        run: |
          rustup default stable
          rustc -vV
          cargo -vV

      - name: Build
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cargo build --release 
          else
            cargo build --release 
            mv target/release/hexsaly target/release/hexsaly.bin
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hexsaly-${{ matrix.os == 'ubuntu-latest' && 'Linux' || 'Windows' }}
          path: target/release/hexsaly${{ matrix.os == 'windows-latest' && '.exe' || '.bin' }}
          if-no-files-found: error