name: CI Builds

on: push

permissions:
  contents: write

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        shell: bash
        run: |
          rustup default stable
          rustc -vV
          cargo -vV

      - name: Build
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cargo build --release 
             mv target/release/hexsaly.exe Hexsaly-Windows.exe
          else
            cargo build --release 
            mv target/release/hexsaly Hexsaly-Linux
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Hexsaly-${{ matrix.os == 'ubuntu-latest' && 'Linux' || 'Windows' }}
          path: Hexsaly-*
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          body: |
            # Hexsaly ${{ github.ref_name }}


            [![action](https://img.shields.io/badge/build-action-brightgreen?style=for-the-badge&logo=cargo&labelColor=%231e1e2e&color=%23a6e3a1)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          files: Hexsaly-*
